#!/usr/bin/env bash

# Deployment helper - shows available commands and usage
echo "🚀 NixOS Homelab Deployment Helper"
echo "=================================="
echo ""
echo "Available machines: hugin, munin"
echo ""
echo "📦 Local Operations:"
echo "  ./nix-helper.sh flake show                    # Show configurations"
echo "  ./nix-helper.sh flake check                   # Check for errors"
echo "  ./nix-helper.sh build .#nixosConfigurations.hugin.config.system.build.toplevel"
echo ""
echo "🌐 Remote Deployment (to existing NixOS machines):"
echo "  ./deploy.sh hugin root@192.168.1.100          # Deploy hugin config"
echo "  ./deploy.sh munin root@192.168.1.101          # Deploy munin config"
echo ""
echo "💿 Fresh Installation (⚠️  WIPES TARGET MACHINE):"
echo "  ./install-fresh.sh hugin root@192.168.1.100   # Fresh install hugin"
echo "  ./install-fresh.sh munin root@192.168.1.101   # Fresh install munin"
echo ""
echo "📋 Prerequisites for remote deployment:"
echo "  • SSH key-based authentication to target hosts"
echo "  • Target hosts must be reachable via SSH"
echo "  • For fresh installs: machines must be booted from NixOS installer"
echo ""
echo "🔧 Troubleshooting:"
echo "  ./setup-ssh.sh root@192.168.50.210        # Diagnose SSH issues"
echo "  ssh-copy-id root@192.168.50.210           # Copy SSH key to target"
echo "  ssh root@192.168.50.210                   # Test manual SSH connection"
echo ""
echo "🧹 Cleanup and Maintenance:"
echo "  ./cleanup.sh --list                       # Show GC roots"
echo "  ./cleanup.sh --remove-roots               # Remove result symlinks"
echo "  ./cleanup.sh --garbage                    # Run garbage collection"
echo "  ./cleanup.sh --all                        # Clean everything"
echo ""
echo "💡 Tips:"
echo "  • Always run 'flake check' before deploying"
echo "  • Test configurations locally first"
echo "  • Keep SSH keys in ~/.ssh/ with proper permissions"